<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
	function ($class) {
		static $classes = null;
		if ($classes === null) {
			$classes = [
				'xicrow\\phpcollection\\basecollection'               => '/BaseCollection.php',
				'xicrow\\phpcollection\\object\\baseobjectcollection' => '/Object/BaseObjectCollection.php',
				'xicrow\\phpcollection\\object\\datetimecollection'   => '/Object/DateTimeCollection.php',
				'xicrow\\phpcollection\\scalar\\basescalarcollection' => '/Scalar/BaseScalarCollection.php',
				'xicrow\\phpcollection\\scalar\\booleancollection'    => '/Scalar/BooleanCollection.php',
				'xicrow\\phpcollection\\scalar\\floatcollection'      => '/Scalar/FloatCollection.php',
				'xicrow\\phpcollection\\scalar\\integercollection'    => '/Scalar/IntegerCollection.php',
				'xicrow\\phpcollection\\scalar\\stringcollection'     => '/Scalar/StringCollection.php',
			];
		}
		$cn = strtolower($class);
		if (isset($classes[$cn])) {
			require __DIR__ . $classes[$cn];
		}
	},
	true,
	false
);
// @codeCoverageIgnoreEnd
